# Generated by Django 5.0.6 on 2024-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
