# Generated by Django 5.0.6 on 2024-05-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_acounts_delete_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acounts',
            new_name='members_users',
        ),
    ]
