# Generated by Django 5.0.6 on 2024-05-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_acounts_members_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('idInput', models.CharField(max_length=100, unique=True)),
                ('yearsInput', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('about_us', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('required', models.CharField(max_length=300)),
                ('loc', models.CharField(max_length=100)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Hours', models.IntegerField()),
                ('companyname', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='members_users',
            name='companyName',
        ),
        migrations.AlterField(
            model_name='members_users',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='members_users',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='members_users',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='members_users',
            name='companyname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
