# Generated by Django 5.0.6 on 2024-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_jobs_remove_members_users_companyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='idInput',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
