# Generated by Django 5.0.6 on 2024-05-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_jobs_id_alter_jobs_idinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyjobs',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('idInput', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
